<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="LAPTOP-SQBD1KF4" failures="1" tests="2" name="Default test(failed)(failed)" time="5.167" errors="0" timestamp="2023-01-05T11:55:06 IST">
  <testcase classname="TestCases.FailedTest" name="test3" time="0.044">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at TestCases.FailedTest.test3(FailedTest.java:40)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase classname="TestCases.FailedTest" name="test1" time="0.033"/>
  <testcase classname="TestCases.FailedTest" name="test2" time="0.0">
    <ignored/>
  </testcase> <!-- test2 -->
  <testcase classname="TestCases.FailedTest" name="test4" time="0.0">
    <ignored/>
  </testcase> <!-- test4 -->
  <testcase classname="TestCases.FailedTest" name="test5" time="0.0">
    <ignored/>
  </testcase> <!-- test5 -->
</testsuite> <!-- Default test(failed)(failed) -->
